import type { NextPage } from 'next'
import Head from 'next/head'
import SearchBar from '../components/SearchBar'
import PokemonList from '../components/PokemonList'

const Home: NextPage = () => {

  return (
    <div className="p-5">
      <Head>
        <title>Pokemon List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchBar/>
      <div>
        <PokemonList/>
      </div>
    </div>
  )
}

export default Home
